### ISSUE TITLE
Unexpected token '.' 

### ISSUE THREAD

**Issue by a-eid** [klarna-incubator/platform-colors#27]
![Screen Shot 2021-12-04 at 12 07 56 AM](https://user-images.githubusercontent.com/19273413/144679293-91e7d914-885e-4098-861f-4fb5c4fe82e0.png)

same issue happens with the example app.

![Screen Shot 2021-12-04 at 12 18 03 AM](https://user-images.githubusercontent.com/19273413/144680299-54c622ad-8271-4e44-bc89-4423629b1f35.png)

![Screen Shot 2021-12-04 at 12 18 24 AM](https://user-images.githubusercontent.com/19273413/144680341-089bda73-2393-4e6d-82f1-0b2a12574887.png)

STR: 

- init a new react-native project 
- run `npx @klarna/platform-colors` in the root directory

**Comment by oblador** [comment]
Which version of node are you on? I think this is probably too fancy/new syntax @pontusab

**Comment by pontusab** [comment]
yeah true, I can have a look

**Comment by a-eid** [comment]
> Which version of node are you on? I think this is probably too fancy/new syntax @pontusab

`v12.22.7`

**Comment by a-eid** [comment]
rerunning the command produces this error.

![Screen Shot 2021-12-04 at 12 50 15 PM](https://user-images.githubusercontent.com/19273413/144706775-1a5deb13-c3e2-4942-971f-5916bde7f774.png)


also android is not working unless I reload the app.

**Comment by a-eid** [comment]
https://user-images.githubusercontent.com/19273413/144706899-59512982-199f-4131-bdff-b1cdf8a4f132.mp4

**Comment by a-eid** [comment]
> Dec-04-2021.12-55-11.mp4

I think this was an issue with my simulator.

**Comment by yangm97** [comment]
The xml parser won't output an array if `values.xml` contains only one color, which breaks that filter. As a workaround you can try adding another color there.

**Comment by a-eid** [comment]
```patch
diff --git a/node_modules/@klarna/platform-colors/src/templates/android.js b/node_modules/@klarna/platform-colors/src/templates/android.js
index ecdcb6e..599b356 100644
--- a/node_modules/@klarna/platform-colors/src/templates/android.js
+++ b/node_modules/@klarna/platform-colors/src/templates/android.js
@@ -1,7 +1,8 @@
 const path = require('path');
 const { create, convert } = require('xmlbuilder2');
 const fs = require('fs-extra');
-const { formatName } = require('../utils');
+const { formatName, ensureAndoridFiles } = require('../utils');
+
 
 function stringifyColor(color) {
   const hex = color.hex();
@@ -16,6 +17,7 @@ const getXmlResources = (config, filename) => {
   const outputDirectory = config?.android?.outputDirectory;
 
   if (outputDirectory) {
+    ensureAndoridFiles(outputDirectory);
     const xml = fs
       .readFileSync(path.resolve(outputDirectory, filename))
       .toString();
diff --git a/node_modules/@klarna/platform-colors/src/utils.js b/node_modules/@klarna/platform-colors/src/utils.js
index bdb7cce..3d99317 100644
--- a/node_modules/@klarna/platform-colors/src/utils.js
+++ b/node_modules/@klarna/platform-colors/src/utils.js
@@ -6,10 +6,13 @@ const {
   sentenceCase,
 } = require('change-case');
 
+const path = require('path');
+const fs = require('fs-extra');
+
 const DEFAULT_PREFIX = 'rnpc';
 
 function formatName(platform, config, name = '') {
-  const prefix = config?.prefix || DEFAULT_PREFIX;
+  const prefix = (config && config.prefix) || DEFAULT_PREFIX;
 
   switch (platform) {
     case 'android':
@@ -23,6 +26,14 @@ function formatName(platform, config, name = '') {
   }
 }
 
+function ensureAndoridFiles(outputDirectory) {
+  fs.ensureFileSync(
+    path.resolve(`${outputDirectory}/values-night/`, 'colors.xml')
+  );
+  fs.ensureFileSync(path.resolve(`${outputDirectory}/values/`, 'colors.xml'));
+}
+
 module.exports = {
   formatName,
+  ensureAndoridFiles
 };
```

@pontusab  I applied both fixes as a patch file and am still getting the following error.

![Screen Shot 2022-01-21 at 2 52 20 PM](https://user-images.githubusercontent.com/19273413/150530084-fa16bb5e-fc65-44ee-85c0-85632550651f.png)

**Comment by a-eid** [comment]
![Screen Shot 2022-01-21 at 2 58 53 PM](https://user-images.githubusercontent.com/19273413/150530988-f2c76d4e-bd93-4a2e-94cf-6dd6cbdcc992.png)


had to add this line to fix it.

thank you

**Comment by a-eid** [comment]
one note is that, you have to have at least 1 color inside of your `values-night/colors.xml` file.

**Comment by pontusab** [comment]
I updated the PR resolving this, also node >= v12 from now on is supported!
